//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SplitTrailers.SplittrailerReferencia {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSplitTrailerSoap", Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class WebSplitTrailer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertaDatosClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraePedidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeDetallePedidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaetiquetaleidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarNonQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarcajaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaCajaPreesplitOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeinfoOrdenOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeinfosurprodOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerecibosdisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ejecutarconsultaExcalarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebSplitTrailer() {
            this.Url = "http://189.206.160.206:81/EmbarquesApk/WebServiceSplitTrailer/WebSplitTrailer.asm" +
                "x";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertaDatosClientesCompletedEventHandler InsertaDatosClientesCompleted;
        
        /// <remarks/>
        public event GetCustomerListCompletedEventHandler GetCustomerListCompleted;
        
        /// <remarks/>
        public event TraePedidosCompletedEventHandler TraePedidosCompleted;
        
        /// <remarks/>
        public event TraeDetallePedidosCompletedEventHandler TraeDetallePedidosCompleted;
        
        /// <remarks/>
        public event validaetiquetaleidaCompletedEventHandler validaetiquetaleidaCompleted;
        
        /// <remarks/>
        public event InsertarNonQueryCompletedEventHandler InsertarNonQueryCompleted;
        
        /// <remarks/>
        public event validarcajaCompletedEventHandler validarcajaCompleted;
        
        /// <remarks/>
        public event ValidaCajaPreesplitCompletedEventHandler ValidaCajaPreesplitCompleted;
        
        /// <remarks/>
        public event TraeinfoOrdenCompletedEventHandler TraeinfoOrdenCompleted;
        
        /// <remarks/>
        public event TraeinfosurprodCompletedEventHandler TraeinfosurprodCompleted;
        
        /// <remarks/>
        public event TraerecibosdisponiblesCompletedEventHandler TraerecibosdisponiblesCompleted;
        
        /// <remarks/>
        public event ejecutarconsultaExcalarCompletedEventHandler ejecutarconsultaExcalarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/InsertaDatosClientes", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertaDatosClientes(string nom, string tel, string ciu) {
            object[] results = this.Invoke("InsertaDatosClientes", new object[] {
                        nom,
                        tel,
                        ciu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaDatosClientesAsync(string nom, string tel, string ciu) {
            this.InsertaDatosClientesAsync(nom, tel, ciu, null);
        }
        
        /// <remarks/>
        public void InsertaDatosClientesAsync(string nom, string tel, string ciu, object userState) {
            if ((this.InsertaDatosClientesOperationCompleted == null)) {
                this.InsertaDatosClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaDatosClientesOperationCompleted);
            }
            this.InvokeAsync("InsertaDatosClientes", new object[] {
                        nom,
                        tel,
                        ciu}, this.InsertaDatosClientesOperationCompleted, userState);
        }
        
        private void OnInsertaDatosClientesOperationCompleted(object arg) {
            if ((this.InsertaDatosClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaDatosClientesCompleted(this, new InsertaDatosClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/GetCustomerList", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Armadores[] GetCustomerList() {
            object[] results = this.Invoke("GetCustomerList", new object[0]);
            return ((Armadores[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerListAsync() {
            this.GetCustomerListAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerListAsync(object userState) {
            if ((this.GetCustomerListOperationCompleted == null)) {
                this.GetCustomerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerListOperationCompleted);
            }
            this.InvokeAsync("GetCustomerList", new object[0], this.GetCustomerListOperationCompleted, userState);
        }
        
        private void OnGetCustomerListOperationCompleted(object arg) {
            if ((this.GetCustomerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerListCompleted(this, new GetCustomerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/TraePedidos", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedidos[] TraePedidos(string cve_cliente, string fecha_trailer) {
            object[] results = this.Invoke("TraePedidos", new object[] {
                        cve_cliente,
                        fecha_trailer});
            return ((Pedidos[])(results[0]));
        }
        
        /// <remarks/>
        public void TraePedidosAsync(string cve_cliente, string fecha_trailer) {
            this.TraePedidosAsync(cve_cliente, fecha_trailer, null);
        }
        
        /// <remarks/>
        public void TraePedidosAsync(string cve_cliente, string fecha_trailer, object userState) {
            if ((this.TraePedidosOperationCompleted == null)) {
                this.TraePedidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraePedidosOperationCompleted);
            }
            this.InvokeAsync("TraePedidos", new object[] {
                        cve_cliente,
                        fecha_trailer}, this.TraePedidosOperationCompleted, userState);
        }
        
        private void OnTraePedidosOperationCompleted(object arg) {
            if ((this.TraePedidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraePedidosCompleted(this, new TraePedidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/TraeDetallePedidos", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public detallePedidos[] TraeDetallePedidos(string placa, string fecha_trailer) {
            object[] results = this.Invoke("TraeDetallePedidos", new object[] {
                        placa,
                        fecha_trailer});
            return ((detallePedidos[])(results[0]));
        }
        
        /// <remarks/>
        public void TraeDetallePedidosAsync(string placa, string fecha_trailer) {
            this.TraeDetallePedidosAsync(placa, fecha_trailer, null);
        }
        
        /// <remarks/>
        public void TraeDetallePedidosAsync(string placa, string fecha_trailer, object userState) {
            if ((this.TraeDetallePedidosOperationCompleted == null)) {
                this.TraeDetallePedidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeDetallePedidosOperationCompleted);
            }
            this.InvokeAsync("TraeDetallePedidos", new object[] {
                        placa,
                        fecha_trailer}, this.TraeDetallePedidosOperationCompleted, userState);
        }
        
        private void OnTraeDetallePedidosOperationCompleted(object arg) {
            if ((this.TraeDetallePedidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeDetallePedidosCompleted(this, new TraeDetallePedidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/validaetiquetaleida", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public detallePedidos[] validaetiquetaleida(string placa, string fecha_trailer) {
            object[] results = this.Invoke("validaetiquetaleida", new object[] {
                        placa,
                        fecha_trailer});
            return ((detallePedidos[])(results[0]));
        }
        
        /// <remarks/>
        public void validaetiquetaleidaAsync(string placa, string fecha_trailer) {
            this.validaetiquetaleidaAsync(placa, fecha_trailer, null);
        }
        
        /// <remarks/>
        public void validaetiquetaleidaAsync(string placa, string fecha_trailer, object userState) {
            if ((this.validaetiquetaleidaOperationCompleted == null)) {
                this.validaetiquetaleidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaetiquetaleidaOperationCompleted);
            }
            this.InvokeAsync("validaetiquetaleida", new object[] {
                        placa,
                        fecha_trailer}, this.validaetiquetaleidaOperationCompleted, userState);
        }
        
        private void OnvalidaetiquetaleidaOperationCompleted(object arg) {
            if ((this.validaetiquetaleidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaetiquetaleidaCompleted(this, new validaetiquetaleidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/InsertarNonQuery", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarNonQuery(string consulta) {
            object[] results = this.Invoke("InsertarNonQuery", new object[] {
                        consulta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarNonQueryAsync(string consulta) {
            this.InsertarNonQueryAsync(consulta, null);
        }
        
        /// <remarks/>
        public void InsertarNonQueryAsync(string consulta, object userState) {
            if ((this.InsertarNonQueryOperationCompleted == null)) {
                this.InsertarNonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarNonQueryOperationCompleted);
            }
            this.InvokeAsync("InsertarNonQuery", new object[] {
                        consulta}, this.InsertarNonQueryOperationCompleted, userState);
        }
        
        private void OnInsertarNonQueryOperationCompleted(object arg) {
            if ((this.InsertarNonQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarNonQueryCompleted(this, new InsertarNonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/validarcaja", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string validarcaja(string cadena) {
            object[] results = this.Invoke("validarcaja", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validarcajaAsync(string cadena) {
            this.validarcajaAsync(cadena, null);
        }
        
        /// <remarks/>
        public void validarcajaAsync(string cadena, object userState) {
            if ((this.validarcajaOperationCompleted == null)) {
                this.validarcajaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarcajaOperationCompleted);
            }
            this.InvokeAsync("validarcaja", new object[] {
                        cadena}, this.validarcajaOperationCompleted, userState);
        }
        
        private void OnvalidarcajaOperationCompleted(object arg) {
            if ((this.validarcajaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarcajaCompleted(this, new validarcajaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/ValidaCajaPreesplit", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidaCajaPreesplit(string cadena) {
            object[] results = this.Invoke("ValidaCajaPreesplit", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaCajaPreesplitAsync(string cadena) {
            this.ValidaCajaPreesplitAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ValidaCajaPreesplitAsync(string cadena, object userState) {
            if ((this.ValidaCajaPreesplitOperationCompleted == null)) {
                this.ValidaCajaPreesplitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaCajaPreesplitOperationCompleted);
            }
            this.InvokeAsync("ValidaCajaPreesplit", new object[] {
                        cadena}, this.ValidaCajaPreesplitOperationCompleted, userState);
        }
        
        private void OnValidaCajaPreesplitOperationCompleted(object arg) {
            if ((this.ValidaCajaPreesplitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaCajaPreesplitCompleted(this, new ValidaCajaPreesplitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/TraeinfoOrden", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public infoprod[] TraeinfoOrden(int diascad, string mtip, string mcod, string mfol, int mtar) {
            object[] results = this.Invoke("TraeinfoOrden", new object[] {
                        diascad,
                        mtip,
                        mcod,
                        mfol,
                        mtar});
            return ((infoprod[])(results[0]));
        }
        
        /// <remarks/>
        public void TraeinfoOrdenAsync(int diascad, string mtip, string mcod, string mfol, int mtar) {
            this.TraeinfoOrdenAsync(diascad, mtip, mcod, mfol, mtar, null);
        }
        
        /// <remarks/>
        public void TraeinfoOrdenAsync(int diascad, string mtip, string mcod, string mfol, int mtar, object userState) {
            if ((this.TraeinfoOrdenOperationCompleted == null)) {
                this.TraeinfoOrdenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeinfoOrdenOperationCompleted);
            }
            this.InvokeAsync("TraeinfoOrden", new object[] {
                        diascad,
                        mtip,
                        mcod,
                        mfol,
                        mtar}, this.TraeinfoOrdenOperationCompleted, userState);
        }
        
        private void OnTraeinfoOrdenOperationCompleted(object arg) {
            if ((this.TraeinfoOrdenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeinfoOrdenCompleted(this, new TraeinfoOrdenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/Traeinfosurprod", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public recibosvencidos[] Traeinfosurprod(string mtip, string mcod, string mfol, int mtar) {
            object[] results = this.Invoke("Traeinfosurprod", new object[] {
                        mtip,
                        mcod,
                        mfol,
                        mtar});
            return ((recibosvencidos[])(results[0]));
        }
        
        /// <remarks/>
        public void TraeinfosurprodAsync(string mtip, string mcod, string mfol, int mtar) {
            this.TraeinfosurprodAsync(mtip, mcod, mfol, mtar, null);
        }
        
        /// <remarks/>
        public void TraeinfosurprodAsync(string mtip, string mcod, string mfol, int mtar, object userState) {
            if ((this.TraeinfosurprodOperationCompleted == null)) {
                this.TraeinfosurprodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeinfosurprodOperationCompleted);
            }
            this.InvokeAsync("Traeinfosurprod", new object[] {
                        mtip,
                        mcod,
                        mfol,
                        mtar}, this.TraeinfosurprodOperationCompleted, userState);
        }
        
        private void OnTraeinfosurprodOperationCompleted(object arg) {
            if ((this.TraeinfosurprodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeinfosurprodCompleted(this, new TraeinfosurprodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/Traerecibosdisponibles", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public recibosdisponibles[] Traerecibosdisponibles(int diascad, string prod, string mtip) {
            object[] results = this.Invoke("Traerecibosdisponibles", new object[] {
                        diascad,
                        prod,
                        mtip});
            return ((recibosdisponibles[])(results[0]));
        }
        
        /// <remarks/>
        public void TraerecibosdisponiblesAsync(int diascad, string prod, string mtip) {
            this.TraerecibosdisponiblesAsync(diascad, prod, mtip, null);
        }
        
        /// <remarks/>
        public void TraerecibosdisponiblesAsync(int diascad, string prod, string mtip, object userState) {
            if ((this.TraerecibosdisponiblesOperationCompleted == null)) {
                this.TraerecibosdisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerecibosdisponiblesOperationCompleted);
            }
            this.InvokeAsync("Traerecibosdisponibles", new object[] {
                        diascad,
                        prod,
                        mtip}, this.TraerecibosdisponiblesOperationCompleted, userState);
        }
        
        private void OnTraerecibosdisponiblesOperationCompleted(object arg) {
            if ((this.TraerecibosdisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerecibosdisponiblesCompleted(this, new TraerecibosdisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://189.206.160.206:81/WebServiceSplitTrailer/ejecutarconsultaExcalar", RequestNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", ResponseNamespace="http://189.206.160.206:81/WebServiceSplitTrailer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ejecutarconsultaExcalar(string cadena) {
            object[] results = this.Invoke("ejecutarconsultaExcalar", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ejecutarconsultaExcalarAsync(string cadena) {
            this.ejecutarconsultaExcalarAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ejecutarconsultaExcalarAsync(string cadena, object userState) {
            if ((this.ejecutarconsultaExcalarOperationCompleted == null)) {
                this.ejecutarconsultaExcalarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnejecutarconsultaExcalarOperationCompleted);
            }
            this.InvokeAsync("ejecutarconsultaExcalar", new object[] {
                        cadena}, this.ejecutarconsultaExcalarOperationCompleted, userState);
        }
        
        private void OnejecutarconsultaExcalarOperationCompleted(object arg) {
            if ((this.ejecutarconsultaExcalarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ejecutarconsultaExcalarCompleted(this, new ejecutarconsultaExcalarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class Armadores {
        
        private string nombreField;
        
        private string idField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class recibosdisponibles {
        
        private string disponibleField;
        
        private string fecha_cadField;
        
        private string reciboField;
        
        private string tarimaField;
        
        /// <remarks/>
        public string disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        public string fecha_cad {
            get {
                return this.fecha_cadField;
            }
            set {
                this.fecha_cadField = value;
            }
        }
        
        /// <remarks/>
        public string recibo {
            get {
                return this.reciboField;
            }
            set {
                this.reciboField = value;
            }
        }
        
        /// <remarks/>
        public string tarima {
            get {
                return this.tarimaField;
            }
            set {
                this.tarimaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class recibosvencidos {
        
        private string pRODField;
        
        private string sURTIDOField;
        
        private string fECCADField;
        
        private string estatus_surField;
        
        /// <remarks/>
        public string PROD {
            get {
                return this.pRODField;
            }
            set {
                this.pRODField = value;
            }
        }
        
        /// <remarks/>
        public string SURTIDO {
            get {
                return this.sURTIDOField;
            }
            set {
                this.sURTIDOField = value;
            }
        }
        
        /// <remarks/>
        public string FECCAD {
            get {
                return this.fECCADField;
            }
            set {
                this.fECCADField = value;
            }
        }
        
        /// <remarks/>
        public string estatus_sur {
            get {
                return this.estatus_surField;
            }
            set {
                this.estatus_surField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class infoprod {
        
        private string pRODField;
        
        private string sURTIDOField;
        
        private string fECCADField;
        
        private string fecha_cadField;
        
        /// <remarks/>
        public string PROD {
            get {
                return this.pRODField;
            }
            set {
                this.pRODField = value;
            }
        }
        
        /// <remarks/>
        public string SURTIDO {
            get {
                return this.sURTIDOField;
            }
            set {
                this.sURTIDOField = value;
            }
        }
        
        /// <remarks/>
        public string FECCAD {
            get {
                return this.fECCADField;
            }
            set {
                this.fECCADField = value;
            }
        }
        
        /// <remarks/>
        public string fecha_cad {
            get {
                return this.fecha_cadField;
            }
            set {
                this.fecha_cadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class detallePedidos {
        
        private string productonombreField;
        
        private string detalleField;
        
        private string cantidadField;
        
        /// <remarks/>
        public string productonombre {
            get {
                return this.productonombreField;
            }
            set {
                this.productonombreField = value;
            }
        }
        
        /// <remarks/>
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9339.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://189.206.160.206:81/WebServiceSplitTrailer")]
    public partial class Pedidos {
        
        private string no_trailerField;
        
        private string transporteField;
        
        private string choferField;
        
        /// <remarks/>
        public string no_trailer {
            get {
                return this.no_trailerField;
            }
            set {
                this.no_trailerField = value;
            }
        }
        
        /// <remarks/>
        public string transporte {
            get {
                return this.transporteField;
            }
            set {
                this.transporteField = value;
            }
        }
        
        /// <remarks/>
        public string chofer {
            get {
                return this.choferField;
            }
            set {
                this.choferField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertaDatosClientesCompletedEventHandler(object sender, InsertaDatosClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaDatosClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaDatosClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetCustomerListCompletedEventHandler(object sender, GetCustomerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Armadores[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Armadores[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraePedidosCompletedEventHandler(object sender, TraePedidosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraePedidosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraePedidosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedidos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedidos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraeDetallePedidosCompletedEventHandler(object sender, TraeDetallePedidosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeDetallePedidosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeDetallePedidosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public detallePedidos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((detallePedidos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void validaetiquetaleidaCompletedEventHandler(object sender, validaetiquetaleidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaetiquetaleidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaetiquetaleidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public detallePedidos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((detallePedidos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertarNonQueryCompletedEventHandler(object sender, InsertarNonQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void validarcajaCompletedEventHandler(object sender, validarcajaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarcajaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarcajaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidaCajaPreesplitCompletedEventHandler(object sender, ValidaCajaPreesplitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaCajaPreesplitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaCajaPreesplitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraeinfoOrdenCompletedEventHandler(object sender, TraeinfoOrdenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeinfoOrdenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeinfoOrdenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public infoprod[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((infoprod[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraeinfosurprodCompletedEventHandler(object sender, TraeinfosurprodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeinfosurprodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeinfosurprodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public recibosvencidos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((recibosvencidos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraerecibosdisponiblesCompletedEventHandler(object sender, TraerecibosdisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerecibosdisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerecibosdisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public recibosdisponibles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((recibosdisponibles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ejecutarconsultaExcalarCompletedEventHandler(object sender, ejecutarconsultaExcalarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ejecutarconsultaExcalarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ejecutarconsultaExcalarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591